name: Build and Upload

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install json
          pip install pyyaml
          pip install xmltodict

      - name: Install project resources
        run: |
          ./installResources.ps1

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole project.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: program
          path: dist/project.exe